# Generated by Django 3.2.10 on 2021-12-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('postTitle', models.CharField(max_length=100)),
                ('postContent', models.CharField(max_length=500)),
            ],
        ),
    ]
